### ISSUE TITLE
BCIC-IV-2a dataset mat-files

### ISSUE THREAD

**Issue by PappaBu** [CECNL/MAtt#1]
@CECNL Thanks for the description of the novel MAtt network and for the source code. I can't reproduce results for BCIC-IV-2a dataset. The [link to the dataset](https://www.bbci.de/competition/iv/#dataset2a) you provided contains EEG recordings in GDF format only. But your code requires mat-files.

I found another [BCIC-IV-2a dataset source](http://bnci-horizon-2020.eu/database/data-sets) with mat-files, but the following error occurred while preparing the data:

```
~/MAtt-main/utils/GetBci2a.py in getAllDataloader(subject, ratio, data_path, bs)
     38     train = io.loadmat(os.path.join(data_path, 'BCIC_S' + f'{subject:02d}' + '_T.mat'))
     39     test = io.loadmat(os.path.join(data_path, 'BCIC_S' + f'{subject:02d}' + '_E.mat'))
     40 
---> 41     x_train = torch.Tensor(train['x_train']).unsqueeze(1)
     42     y_train = torch.Tensor(train['y_train']).view(-1)

KeyError: 'x_train'
```

As far as I understand, you are using a custom BCIC-IV-2a dataset mat-files format.

Please provide a description of the used mat-files format (for example, format for the BCIC_S01_T.mat and BCIC_S01_E.mat) or a link to download these files. Without mat-files it is impossible to reproduce your results.

**Comment by PappaBu** [comment]
Thanks for providing the link to the dataset. Now everything works as described.

**Comment by Murphyzc** [comment]
I meet the same question, could you share your datasets?

**Comment by JoBurchert** [comment]
I am also interested in the datasets, however, the files got deleted in your drive location when following the link in the dataset section. Could you be so kind as to restore the files?

**Comment by CECNL** [comment]
@Murphyzc @JoBurchert Oh! my account was deleted by my university because I already graduated. I apologize for the inconvenience. I found the same file in my backup and uploaded it to the Google Drive of another account, thus you can check again now. Thank you!
