### ISSUE TITLE
Found a bug when getting the x_train dataset

### ISSUE THREAD

**Issue by liquanoba** [CECNL/MAtt#4]
Try to get x_train dataset  through the code:  'x_train =torch.Tensor(train['x_train']).unsqueeze(1)' in  GetBci2a.py, occur error :KeyError: 'x_train'

1.  print(train.keys()) not found key '**x_train**' 'y_train' 'y_test' ‘x_test’ contain (['__header__', '__version__', '__globals__', 'data'])
2.   print train dataset info
3.  EEG data have preprocessed?

![133403983034dde45b0b29693f61f18](https://user-images.githubusercontent.com/119591345/230376935-efa2a1b2-cd9f-4f07-881e-617baef82b51.png)
![68004a2df7ef593c5a2051ab8704079](https://user-images.githubusercontent.com/119591345/230376949-089af824-e5e2-4921-a3cc-41b9e1048e18.png)

**Comment by CECNL** [comment]
The data was already be processed in advance.
We also provided the data link on our readme file.
Perhaps you can execute the script after you download the [data](https://drive.google.com/file/d/1_KBfSNzvxCZ-HwiOASQhlFe8wwsq4vHt/view?usp=sharing)
It would be fine if you want to preprocess the data and rewrite the data loader by yourself.
Detail preprocess steps are illustrated in our paper. All preprocessing steps are common operations in EEG signal processing, such as down sample and channel selection.
